#!/bin/bash
#
# Automated greeter for Star Wars crew

SW_CREW=("Leia" "R2D2" "Han Solo" "Chewbakka" "C3PO")

for crew_member in "${SW_CREW[@]}"; do
  echo "Hi ${crew_member}"
done

echo "Hi everyone"
